MCU = atmega8
Q = @
OPT = s

SRC = 
CPPSRC = main.cpp
ASRC =

PROGRAMMER = lm3s811
#Enable debugging (Uses UART @ 38400 baud)
DEBUG = True
###################################################################
SYSTEMDIR = avrbase
include $(SYSTEMDIR)/Makefile.module
